---
title: "uber K-means"
author: "Luyue"
date: "August 29, 2019"
output:
  word_document: default
  pdf_document: default
  html_document: default
---
```{r}
library(rlang)
```

```{r setup, include=FALSE}
apr14 <- read.csv("uber-raw-data-apr14.csv")
may14 <- read.csv("uber-raw-data-may14.csv")
jun14 <- read.csv("uber-raw-data-jun14.csv")
jul14 <- read.csv("uber-raw-data-jul14.csv")
aug14 <- read.csv("uber-raw-data-aug14.csv")
sep14 <- read.csv("uber-raw-data-sep14.csv")
```

```{r}
#bind all data files into one

library(dplyr)


data14 <- bind_rows(apr14,may14,jun14,jul14,aug14,sep14)
summary(data14)
```

```{r}
#data preparation: cleaning and rearranging
# check the sparsity of the dataset and check the amount of missing data
library(VIM) # Visualization and imputation of missing values
#aggr plots the amount of missing values in each column
aggr(data14)
```

```{r}
#shortcut: ctrl+alt+I
# separate Date.Time variable  use lubriate library, lubriate makes it simple for you to identify the order in which the year, month, and data appear
# in your dates and manipulate them
library(lubridate)
data14$Date.Time <- mdy_hms(data14$Date.Time)
head(data14)
```

```{r}
data14$Year <- factor(year(data14$Date.Time))
data14$Month <- factor(month(data14$Date.Time))
data14$Day <- factor(day(data14$Date.Time))
data14$Weekday <- factor(wday(data14$Date.Time))
data14$Hour <- factor(hour(data14$Date.Time))
data14$Minute <- factor(minute(data14$Date.Time))
data14$Second <- factor(second(data14$Date.Time))
head(data14,n=10)
```


```{r}
# divided the data into training and test data
#k=5 the number of boroughs in New York
#Here you are using clustering for classifying the pickup points into various boroughs. The general scenario where you would use clustering is when you want to learn more about your dataset. So you can run clustering several times, investigate the interesting clusters and note down some of the insights you get. 
#Clustering is more of a tool to help you explore a dataset, and should not always be used as an automatic method to classify data.
set.seed(20)
clusters <- kmeans(data14[,2:3],center=5)
```
```{r}
data14$Borough <- as.factor(clusters$cluster)
head(data14)
```
```{r}
str(clusters)
```

```{r}
clusters$size
```


```{r}
#visualize
library(ggplot2)
library(ggmap)
require(devtools)
devtools::install_github("dkahle/ggmap", ref = "tidyup")
register_google(key = "secret##")
NYCMap <- get_map("New York",zoom=10)
ggmap(NYCMap) + geom_point(aes(x = Lon[], y = Lat[], colour = as.factor(Borough)),data = data14) +
  ggtitle("NYC Boroughs using KMean")
```


